// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3KYXMJcZzG2RJ4eIz65t2motSoV0Hz-4',
    appId: '1:1066123805890:web:5d521113c8d85a66d7275b',
    messagingSenderId: '1066123805890',
    projectId: 'parlour-app-1e3b3',
    authDomain: 'parlour-app-1e3b3.firebaseapp.com',
    storageBucket: 'parlour-app-1e3b3.appspot.com',
    measurementId: 'G-W0E0XYJMGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtW9oDI2R71-_q_oBH-MNtb2oTC57kUe4',
    appId: '1:1066123805890:android:dae298f898d27203d7275b',
    messagingSenderId: '1066123805890',
    projectId: 'parlour-app-1e3b3',
    storageBucket: 'parlour-app-1e3b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrxWLhpqdxWyjuvOkvc33BERNttfXf_I8',
    appId: '1:1066123805890:ios:c8cead1845160518d7275b',
    messagingSenderId: '1066123805890',
    projectId: 'parlour-app-1e3b3',
    storageBucket: 'parlour-app-1e3b3.appspot.com',
    iosClientId: '1066123805890-bv4l67cejtulenvr71qh3o4u1v4mbfgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.barbarBookingApp',
  );
}
